package net.pl3x.stairs.block;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.registries.IForgeRegistry;
import net.pl3x.stairs.block.stairs.StairsBasic;
import net.pl3x.stairs.block.stairs.StairsConcrete;
import net.pl3x.stairs.block.stairs.StairsConcretePowder;
import net.pl3x.stairs.block.stairs.StairsCraftingTable;
import net.pl3x.stairs.block.stairs.StairsFalling;
import net.pl3x.stairs.block.stairs.StairsGlass;
import net.pl3x.stairs.block.stairs.StairsGlassStained;
import net.pl3x.stairs.block.stairs.StairsGrass;
import net.pl3x.stairs.block.stairs.StairsHay;
import net.pl3x.stairs.block.stairs.StairsIce;
import net.pl3x.stairs.block.stairs.StairsJukebox;
import net.pl3x.stairs.block.stairs.StairsLeaves;
import net.pl3x.stairs.block.stairs.StairsMagma;
import net.pl3x.stairs.block.stairs.StairsMycelium;
import net.pl3x.stairs.block.stairs.StairsNoteblock;
import net.pl3x.stairs.block.stairs.StairsRedstone;
import net.pl3x.stairs.block.stairs.StairsRedstoneLamp;
import net.pl3x.stairs.block.stairs.StairsRedstoneOre;
import net.pl3x.stairs.block.stairs.StairsSlime;
import net.pl3x.stairs.block.stairs.StairsSoulSand;
import net.pl3x.stairs.block.stairs.StairsSponge;
import net.pl3x.stairs.block.stairs.StairsTerracotta;
import net.pl3x.stairs.block.stairs.StairsWool;
import net.pl3x.stairs.tab.StairsTab;

import java.util.HashSet;
import java.util.Set;

public class ModBlocks {
    public static final Set<BlockBase> __BLOCKS__ = new HashSet<>();

    public static final StairsBasic STAIRS_ANDESITE = new StairsBasic(Material.ROCK, "stairs_andesite", MapColor.STONE).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_ANDESITE_SMOOTH = new StairsBasic(Material.ROCK, "stairs_andesite_smooth", MapColor.STONE).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_BEDROCK = new StairsBasic(Material.ROCK, "stairs_bedrock", MapColor.STONE).setHardness(-1F).setResistance(6000000F).setSoundType(SoundType.STONE).disableStats();
    public static final StairsBasic STAIRS_BONE = new StairsBasic(Material.ROCK, "stairs_bone", MapColor.SAND).setHardness(2F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_BOOKSHELF = new StairsBasic(Material.WOOD, "stairs_bookshelf", MapColor.WOOD).setHardness(1.5F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_CLAY = new StairsBasic(Material.CLAY, "stairs_clay", MapColor.CLAY).setHardness(0.6F).setSoundType(SoundType.GROUND);
    public static final StairsBasic STAIRS_COAL = new StairsBasic(Material.ROCK, "stairs_coal", MapColor.BLACK).setHardness(5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_COAL_ORE = new StairsBasic(Material.ROCK, "stairs_coal_ore", MapColor.STONE).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_COBBLESTONE_MOSSY = new StairsBasic(Material.ROCK, "stairs_cobblestone_mossy", MapColor.STONE).setHardness(1F).setSoundType(SoundType.STONE);
    public static final StairsConcrete STAIRS_CONCRETE_BLACK = new StairsConcrete(EnumDyeColor.BLACK);
    public static final StairsConcrete STAIRS_CONCRETE_BLUE = new StairsConcrete(EnumDyeColor.BLUE);
    public static final StairsConcrete STAIRS_CONCRETE_BROWN = new StairsConcrete(EnumDyeColor.BROWN);
    public static final StairsConcrete STAIRS_CONCRETE_CYAN = new StairsConcrete(EnumDyeColor.CYAN);
    public static final StairsConcrete STAIRS_CONCRETE_GRAY = new StairsConcrete(EnumDyeColor.GRAY);
    public static final StairsConcrete STAIRS_CONCRETE_GREEN = new StairsConcrete(EnumDyeColor.GREEN);
    public static final StairsConcrete STAIRS_CONCRETE_LIGHT_BLUE = new StairsConcrete(EnumDyeColor.LIGHT_BLUE);
    public static final StairsConcrete STAIRS_CONCRETE_LIME = new StairsConcrete(EnumDyeColor.LIME);
    public static final StairsConcrete STAIRS_CONCRETE_MAGENTA = new StairsConcrete(EnumDyeColor.MAGENTA);
    public static final StairsConcrete STAIRS_CONCRETE_ORANGE = new StairsConcrete(EnumDyeColor.ORANGE);
    public static final StairsConcrete STAIRS_CONCRETE_PINK = new StairsConcrete(EnumDyeColor.PINK);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_BLACK = new StairsConcretePowder(EnumDyeColor.BLACK);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_BLUE = new StairsConcretePowder(EnumDyeColor.BLUE);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_BROWN = new StairsConcretePowder(EnumDyeColor.BROWN);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_CYAN = new StairsConcretePowder(EnumDyeColor.CYAN);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_GRAY = new StairsConcretePowder(EnumDyeColor.GRAY);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_GREEN = new StairsConcretePowder(EnumDyeColor.GREEN);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_LIGHT_BLUE = new StairsConcretePowder(EnumDyeColor.LIGHT_BLUE);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_LIME = new StairsConcretePowder(EnumDyeColor.LIME);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_MAGENTA = new StairsConcretePowder(EnumDyeColor.MAGENTA);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_ORANGE = new StairsConcretePowder(EnumDyeColor.ORANGE);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_PINK = new StairsConcretePowder(EnumDyeColor.PINK);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_PURPLE = new StairsConcretePowder(EnumDyeColor.PURPLE);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_RED = new StairsConcretePowder(EnumDyeColor.RED);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_SILVER = new StairsConcretePowder(EnumDyeColor.SILVER);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_WHITE = new StairsConcretePowder(EnumDyeColor.WHITE);
    public static final StairsConcretePowder STAIRS_CONCRETE_POWDER_YELLOW = new StairsConcretePowder(EnumDyeColor.YELLOW);
    public static final StairsConcrete STAIRS_CONCRETE_PURPLE = new StairsConcrete(EnumDyeColor.PURPLE);
    public static final StairsConcrete STAIRS_CONCRETE_RED = new StairsConcrete(EnumDyeColor.RED);
    public static final StairsConcrete STAIRS_CONCRETE_SILVER = new StairsConcrete(EnumDyeColor.SILVER);
    public static final StairsConcrete STAIRS_CONCRETE_WHITE = new StairsConcrete(EnumDyeColor.WHITE);
    public static final StairsConcrete STAIRS_CONCRETE_YELLOW = new StairsConcrete(EnumDyeColor.YELLOW);
    public static final StairsCraftingTable STAIRS_CRAFTING_TABLE = new StairsCraftingTable();
    public static final StairsBasic STAIRS_DARK_PRISMARINE = new StairsBasic(Material.ROCK, "stairs_dark_prismarine", MapColor.DIAMOND).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_DIAMOND = new StairsBasic(Material.IRON, "stairs_diamond", MapColor.DIAMOND).setHardness(5F).setResistance(10F).setSoundType(SoundType.METAL);
    public static final StairsBasic STAIRS_DIAMOND_ORE = new StairsBasic(Material.ROCK, "stairs_diamond_ore", MapColor.STONE).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_DIORITE = new StairsBasic(Material.ROCK, "stairs_diorite", MapColor.QUARTZ).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_DIORITE_SMOOTH = new StairsBasic(Material.ROCK, "stairs_diorite_smooth", MapColor.QUARTZ).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_DIRT = new StairsBasic(Material.GROUND, "stairs_dirt", MapColor.DIRT).setHardness(0.5F).setResistance(0.5F).setSoundType(SoundType.GROUND);
    public static final StairsBasic STAIRS_DIRT_COARSE = new StairsBasic(Material.GROUND, "stairs_dirt_coarse", MapColor.DIRT).setHardness(0.5F).setResistance(0.5F).setSoundType(SoundType.GROUND);
    public static final StairsBasic STAIRS_EMERALD = new StairsBasic(Material.IRON, "stairs_emerald", MapColor.EMERALD).setHardness(5F).setResistance(10F).setSoundType(SoundType.METAL);
    public static final StairsBasic STAIRS_EMERALD_ORE = new StairsBasic(Material.ROCK, "stairs_emerald_ore", MapColor.STONE).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_END_BRICKS = new StairsBasic(Material.ROCK, "stairs_end_bricks", MapColor.SAND).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_END_STONE = new StairsBasic(Material.ROCK, "stairs_end_stone", MapColor.SAND).setHardness(3F).setResistance(15F).setSoundType(SoundType.STONE);
    public static final StairsGlass STAIRS_GLASS = new StairsGlass();
    public static final StairsGlassStained STAIRS_GLASS_BLACK = new StairsGlassStained(EnumDyeColor.BLACK);
    public static final StairsGlassStained STAIRS_GLASS_BLUE = new StairsGlassStained(EnumDyeColor.BLUE);
    public static final StairsGlassStained STAIRS_GLASS_BROWN = new StairsGlassStained(EnumDyeColor.BROWN);
    public static final StairsGlassStained STAIRS_GLASS_CYAN = new StairsGlassStained(EnumDyeColor.CYAN);
    public static final StairsGlassStained STAIRS_GLASS_GRAY = new StairsGlassStained(EnumDyeColor.GRAY);
    public static final StairsGlassStained STAIRS_GLASS_GREEN = new StairsGlassStained(EnumDyeColor.GREEN);
    public static final StairsGlassStained STAIRS_GLASS_LIGHT_BLUE = new StairsGlassStained(EnumDyeColor.LIGHT_BLUE);
    public static final StairsGlassStained STAIRS_GLASS_LIME = new StairsGlassStained(EnumDyeColor.LIME);
    public static final StairsGlassStained STAIRS_GLASS_MAGENTA = new StairsGlassStained(EnumDyeColor.MAGENTA);
    public static final StairsGlassStained STAIRS_GLASS_ORANGE = new StairsGlassStained(EnumDyeColor.ORANGE);
    public static final StairsGlassStained STAIRS_GLASS_PINK = new StairsGlassStained(EnumDyeColor.PINK);
    public static final StairsGlassStained STAIRS_GLASS_PURPLE = new StairsGlassStained(EnumDyeColor.PURPLE);
    public static final StairsGlassStained STAIRS_GLASS_RED = new StairsGlassStained(EnumDyeColor.RED);
    public static final StairsGlassStained STAIRS_GLASS_SILVER = new StairsGlassStained(EnumDyeColor.SILVER);
    public static final StairsGlassStained STAIRS_GLASS_WHITE = new StairsGlassStained(EnumDyeColor.WHITE);
    public static final StairsGlassStained STAIRS_GLASS_YELLOW = new StairsGlassStained(EnumDyeColor.YELLOW);
    public static final StairsBasic STAIRS_GLOWSTONE = new StairsBasic(Material.GLASS, "stairs_glowstone", MapColor.SAND).setHardness(0.3F).setSoundType(SoundType.GLASS).setLightLevel(1F);
    public static final StairsBasic STAIRS_GOLD = new StairsBasic(Material.IRON, "stairs_gold", MapColor.GOLD).setHardness(3F).setResistance(10F).setSoundType(SoundType.METAL);
    public static final StairsBasic STAIRS_GOLD_ORE = new StairsBasic(Material.ROCK, "stairs_gold_ore", MapColor.STONE).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_GRANITE = new StairsBasic(Material.ROCK, "stairs_granite", MapColor.DIRT).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_GRANITE_SMOOTH = new StairsBasic(Material.ROCK, "stairs_granite_smooth", MapColor.DIRT).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsGrass STAIRS_GRASS = new StairsGrass();
    public static final StairsFalling STAIRS_GRAVEL = new StairsFalling(Material.SAND, "stairs_gravel", MapColor.STONE).setHardness(0.6F).setSoundType(SoundType.GROUND).setDustColor(-8356741);
    public static final StairsHay STAIRS_HAY = new StairsHay();
    public static final StairsIce STAIRS_ICE = new StairsIce();
    public static final StairsBasic STAIRS_ICE_PACKED = new StairsBasic(Material.PACKED_ICE, "stairs_ice_packed", MapColor.ICE).setHardness(0.5F).setSoundType(SoundType.GLASS).setSlipperiness(0.98F);
    public static final StairsBasic STAIRS_IRON = new StairsBasic(Material.IRON, "stairs_iron", MapColor.IRON).setHardness(5F).setResistance(10F).setSoundType(SoundType.METAL);
    public static final StairsBasic STAIRS_IRON_ORE = new StairsBasic(Material.ROCK, "stairs_iron_ore", MapColor.STONE).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsJukebox STAIRS_JUKEBOX = new StairsJukebox();
    public static final StairsBasic STAIRS_LAPIS = new StairsBasic(Material.IRON, "stairs_lapis", MapColor.LAPIS).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_LAPIS_ORE = new StairsBasic(Material.ROCK, "stairs_lapis_ore", MapColor.STONE).setHardness(3F).setResistance(5F).setSoundType(SoundType.STONE);
    public static final StairsLeaves STAIRS_LEAVES_ACACIA = new StairsLeaves("stairs_leaves_acacia");
    public static final StairsLeaves STAIRS_LEAVES_BIRCH = new StairsLeaves("stairs_leaves_birch");
    public static final StairsLeaves STAIRS_LEAVES_DARK_OAK = new StairsLeaves("stairs_leaves_dark_oak");
    public static final StairsLeaves STAIRS_LEAVES_JUNGLE = new StairsLeaves("stairs_leaves_jungle");
    public static final StairsLeaves STAIRS_LEAVES_OAK = new StairsLeaves("stairs_leaves_oak");
    public static final StairsLeaves STAIRS_LEAVES_SPRUCE = new StairsLeaves("stairs_leaves_spruce");
    public static final StairsBasic STAIRS_LOG_ACACIA = new StairsBasic(Material.WOOD, "stairs_log_acacia", MapColor.ADOBE).setHardness(2F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_LOG_BIRCH = new StairsBasic(Material.WOOD, "stairs_log_birch", MapColor.SAND).setHardness(2F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_LOG_DARK_OAK = new StairsBasic(Material.WOOD, "stairs_log_dark_oak", MapColor.BROWN).setHardness(2F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_LOG_JUNGLE = new StairsBasic(Material.WOOD, "stairs_log_jungle", MapColor.DIRT).setHardness(2F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_LOG_OAK = new StairsBasic(Material.WOOD, "stairs_log_oak", MapColor.WOOD).setHardness(2F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_LOG_SPRUCE = new StairsBasic(Material.WOOD, "stairs_log_spruce", MapColor.OBSIDIAN).setHardness(2F).setSoundType(SoundType.WOOD);
    public static final StairsMagma STAIRS_MAGMA = new StairsMagma();
    public static final StairsBasic STAIRS_MELON = new StairsBasic(Material.GOURD, "stairs_melon", MapColor.LIME).setHardness(1.0F).setSoundType(SoundType.WOOD);
    public static final StairsMycelium STAIRS_MYCELIUM = new StairsMycelium();
    public static final StairsBasic STAIRS_NETHERRACK = new StairsBasic(Material.ROCK, "stairs_netherrack", MapColor.NETHERRACK).setHardness(0.4F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_NETHER_WART = new StairsBasic(Material.GRASS, "stairs_nether_wart", MapColor.RED).setHardness(1F).setSoundType(SoundType.WOOD);
    public static final StairsNoteblock STAIRS_NOTEBLOCK = new StairsNoteblock();
    public static final StairsBasic STAIRS_OBSIDIAN = new StairsBasic(Material.ROCK, "stairs_obsidian", MapColor.BLACK).setHardness(50F).setResistance(2000F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_PODZOL = new StairsBasic(Material.GROUND, "stairs_podzol", MapColor.OBSIDIAN).setHardness(0.5F).setResistance(0.5F).setSoundType(SoundType.GROUND);
    public static final StairsBasic STAIRS_PRISMARINE = new StairsBasic(Material.ROCK, "stairs_prismarine", MapColor.CYAN).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_PRISMARINE_BRICK = new StairsBasic(Material.ROCK, "stairs_prismarine_brick", MapColor.DIAMOND).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_PUMPKIN = new StairsBasic(Material.GOURD, "stairs_pumpkin", MapColor.ADOBE).setHardness(1.0F).setSoundType(SoundType.WOOD);
    public static final StairsBasic STAIRS_PURPUR_PILLAR = new StairsBasic(Material.ROCK, "stairs_purpur_pillar", MapColor.MAGENTA).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_QUARTZ_CHISELED = new StairsBasic(Material.ROCK, "stairs_quartz_chiseled", MapColor.QUARTZ).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_QUARTZ_ORE = new StairsBasic(Material.ROCK, "stairs_quartz_ore", MapColor.NETHERRACK).setHardness(3.0F).setResistance(5.0F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_QUARTZ_PILLAR = new StairsBasic(Material.ROCK, "stairs_quartz_pillar", MapColor.QUARTZ).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_RED_NETHER_BRICK = new StairsBasic(Material.ROCK, "stairs_red_nether_brick", MapColor.NETHERRACK).setHardness(2F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsFalling STAIRS_RED_SAND = new StairsFalling(Material.SAND, "stairs_red_sand", MapColor.ADOBE).setHardness(0.5F).setSoundType(SoundType.SAND).setDustColor(-5679071);
    public static final StairsBasic STAIRS_RED_SANDSTONE_CHISELED = new StairsBasic(Material.ROCK, "stairs_red_sandstone_chiseled", MapColor.ADOBE).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_RED_SANDSTONE_SMOOTH = new StairsBasic(Material.ROCK, "stairs_red_sandstone_smooth", MapColor.ADOBE).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsRedstone STAIRS_REDSTONE = new StairsRedstone();
    public static final StairsRedstoneLamp STAIRS_REDSTONE_LAMP = new StairsRedstoneLamp("stairs_redstone_lamp", false);
    public static final StairsRedstoneLamp STAIRS_REDSTONE_LAMP_LIT = new StairsRedstoneLamp("stairs_redstone_lamp_lit", true);
    public static final StairsRedstoneOre STAIRS_REDSTONE_ORE = new StairsRedstoneOre("stairs_redstone_ore", false);
    public static final StairsRedstoneOre STAIRS_REDSTONE_ORE_LIT = new StairsRedstoneOre("stairs_redstone_ore_lit", true);
    public static final StairsFalling STAIRS_SAND = new StairsFalling(Material.SAND, "stairs_sand", MapColor.SAND).setHardness(0.5F).setSoundType(SoundType.SAND).setDustColor(-2370656);
    public static final StairsBasic STAIRS_SANDSTONE_CHISELED = new StairsBasic(Material.ROCK, "stairs_sandstone_chiseled", MapColor.SAND).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_SANDSTONE_SMOOTH = new StairsBasic(Material.ROCK, "stairs_sandstone_smooth", MapColor.SAND).setHardness(0.8F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_SEA_LANTERN = new StairsBasic(Material.GLASS, "stairs_sea_lantern", MapColor.QUARTZ).setHardness(0.3F).setSoundType(SoundType.GLASS).setLightLevel(1F);
    public static final StairsSlime STAIRS_SLIME = new StairsSlime();
    public static final StairsBasic STAIRS_SNOW = new StairsBasic(Material.CRAFTED_SNOW, "stairs_snow", MapColor.SNOW).setHardness(0.2F).setSoundType(SoundType.SNOW);
    public static final StairsSoulSand STAIRS_SOUL_SAND = new StairsSoulSand();
    public static final StairsSponge STAIRS_SPONGE = new StairsSponge("stairs_sponge", false);
    public static final StairsSponge STAIRS_SPONGE_WET = new StairsSponge("stairs_sponge_wet", true);
    public static final StairsBasic STAIRS_STONE = new StairsBasic(Material.ROCK, "stairs_stone", MapColor.STONE).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_STONE_BRICK_CHISELED = new StairsBasic(Material.ROCK, "stairs_stone_brick_chiseled", MapColor.STONE).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_STONE_BRICK_CRACKED = new StairsBasic(Material.ROCK, "stairs_stone_brick_cracked", MapColor.STONE).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsBasic STAIRS_STONE_BRICK_MOSSY = new StairsBasic(Material.ROCK, "stairs_stone_brick_mossy", MapColor.STONE).setHardness(1.5F).setResistance(10F).setSoundType(SoundType.STONE);
    public static final StairsTerracotta STAIRS_TERRACOTTA = new StairsTerracotta();
    public static final StairsTerracotta STAIRS_TERRACOTTA_BLACK = new StairsTerracotta(EnumDyeColor.BLACK);
    public static final StairsTerracotta STAIRS_TERRACOTTA_BLUE = new StairsTerracotta(EnumDyeColor.BLUE);
    public static final StairsTerracotta STAIRS_TERRACOTTA_BROWN = new StairsTerracotta(EnumDyeColor.BROWN);
    public static final StairsTerracotta STAIRS_TERRACOTTA_CYAN = new StairsTerracotta(EnumDyeColor.CYAN);
    public static final StairsTerracotta STAIRS_TERRACOTTA_GRAY = new StairsTerracotta(EnumDyeColor.GRAY);
    public static final StairsTerracotta STAIRS_TERRACOTTA_GREEN = new StairsTerracotta(EnumDyeColor.GREEN);
    public static final StairsTerracotta STAIRS_TERRACOTTA_LIGHT_BLUE = new StairsTerracotta(EnumDyeColor.LIGHT_BLUE);
    public static final StairsTerracotta STAIRS_TERRACOTTA_LIME = new StairsTerracotta(EnumDyeColor.LIME);
    public static final StairsTerracotta STAIRS_TERRACOTTA_MAGENTA = new StairsTerracotta(EnumDyeColor.MAGENTA);
    public static final StairsTerracotta STAIRS_TERRACOTTA_ORANGE = new StairsTerracotta(EnumDyeColor.ORANGE);
    public static final StairsTerracotta STAIRS_TERRACOTTA_PINK = new StairsTerracotta(EnumDyeColor.PINK);
    public static final StairsTerracotta STAIRS_TERRACOTTA_PURPLE = new StairsTerracotta(EnumDyeColor.PURPLE);
    public static final StairsTerracotta STAIRS_TERRACOTTA_RED = new StairsTerracotta(EnumDyeColor.RED);
    public static final StairsTerracotta STAIRS_TERRACOTTA_SILVER = new StairsTerracotta(EnumDyeColor.SILVER);
    public static final StairsTerracotta STAIRS_TERRACOTTA_WHITE = new StairsTerracotta(EnumDyeColor.WHITE);
    public static final StairsTerracotta STAIRS_TERRACOTTA_YELLOW = new StairsTerracotta(EnumDyeColor.YELLOW);
    public static final StairsBasic STAIRS_TNT = new StairsBasic(Material.TNT, "stairs_tnt", MapColor.TNT).setHardness(0.0F).setSoundType(SoundType.PLANT);
    public static final StairsWool STAIRS_WOOL_BLACK = new StairsWool(EnumDyeColor.BLACK);
    public static final StairsWool STAIRS_WOOL_BLUE = new StairsWool(EnumDyeColor.BLUE);
    public static final StairsWool STAIRS_WOOL_BROWN = new StairsWool(EnumDyeColor.BROWN);
    public static final StairsWool STAIRS_WOOL_CYAN = new StairsWool(EnumDyeColor.CYAN);
    public static final StairsWool STAIRS_WOOL_GRAY = new StairsWool(EnumDyeColor.GRAY);
    public static final StairsWool STAIRS_WOOL_GREEN = new StairsWool(EnumDyeColor.GREEN);
    public static final StairsWool STAIRS_WOOL_LIGHT_BLUE = new StairsWool(EnumDyeColor.LIGHT_BLUE);
    public static final StairsWool STAIRS_WOOL_LIME = new StairsWool(EnumDyeColor.LIME);
    public static final StairsWool STAIRS_WOOL_MAGENTA = new StairsWool(EnumDyeColor.MAGENTA);
    public static final StairsWool STAIRS_WOOL_ORANGE = new StairsWool(EnumDyeColor.ORANGE);
    public static final StairsWool STAIRS_WOOL_PINK = new StairsWool(EnumDyeColor.PINK);
    public static final StairsWool STAIRS_WOOL_PURPLE = new StairsWool(EnumDyeColor.PURPLE);
    public static final StairsWool STAIRS_WOOL_RED = new StairsWool(EnumDyeColor.RED);
    public static final StairsWool STAIRS_WOOL_SILVER = new StairsWool(EnumDyeColor.SILVER);
    public static final StairsWool STAIRS_WOOL_WHITE = new StairsWool(EnumDyeColor.WHITE);
    public static final StairsWool STAIRS_WOOL_YELLOW = new StairsWool(EnumDyeColor.YELLOW);

    public static void register(IForgeRegistry<Block> registry) {
        __BLOCKS__.forEach(registry::register);

        GameRegistry.registerTileEntity(StairsJukebox.TileEntityJukebox.class, STAIRS_JUKEBOX.getRegistryName().toString());
        GameRegistry.registerTileEntity(StairsNoteblock.TileEntityNote.class, STAIRS_NOTEBLOCK.getRegistryName().toString());
    }

    public static void registerItemBlocks(IForgeRegistry<Item> registry) {
        __BLOCKS__.forEach(block -> registry.register(block.createItemBlock()));
    }

    public static void registerModels() {
        __BLOCKS__.forEach(block -> block.registerItemModel(Item.getItemFromBlock(block)));
    }

    public static final CreativeTabs TAB_STAIRS = new StairsTab();
}
